version: "3.1"

services:
  rng:
    image: joseamartinez/dockercoins_rng:1.0
    networks:
    - dockercoins
    ports:
    - "8001:80"
    deploy:
        mode: global

  hasher:
    image: joseamartinez/dockercoins_hasher:1.0
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: joseamartinez/dockercoins_webui:3.0
    networks:
    - dockercoins
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    image: joseamartinez/dockercoins_worker:1.0
    networks:
    - dockercoins
    deploy:
        replicas: 10

networks:
    dockercoins:
